### ISSUE TITLE
Article page structure

### ISSUE THREAD

**Issue by 30ann** [IDEMSInternational/plh-kids-app-content#7]
A page should but not necessarily have the following components in this order:

1. Title
2. Subtitle and an icon
3. Text - introduction
4. Image/ media
5. Text
6. Media(audio/ video) - bearing the title, asset, and transcript of the media
7. Three questions with six responses if available: Radio group responses- at least 1 image available or combo box responses - all text
8. Review

**Comment by lauriemarkle** [comment]
Expand this table to include an additional Section.4 in the data list. Resync to live document. 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-cbe4b872-7fff-8f6d-1929-c0ced23e1246"><div dir="ltr" style="margin-left:0pt;" align="left">
section.3.title::eng
--
section.3.text::eng
section.3.button_text::eng
section.3.extra_text::eng

</div></b>

**Comment by 30ann** [comment]
I have added section 4 to the data list and made changes to the templates.
